### ISSUE TITLE
Controller and labels not correct

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#22]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/f4d92ac6-8522-4b32-aaf2-3b6bb81f6262)

**Comment by jakkusu1** [comment]
test comment

**Comment by Amawers** [comment]
@Verseler  ayaw kalimot pa fix ani ahhh

**Comment by Verseler** [comment]
done 
e push nalang kulang
