### ISSUE TITLE
Create schedule Issue

### ISSUE THREAD

**Issue by Verseler** [Amawers/attendifyyy#25]
dili maka create of schedule pag pindot nako sa create button

![image](https://github.com/Amawers/attendifyyy/assets/121875436/da9f4377-c9de-4ab1-944a-e530729d5a4f)

**Comment by Amawers** [comment]
mao na akong wala pa na implement nga backend

**Comment by Amawers** [comment]
done create_schedule api integration, comment lang if okay na sa imo para ma close nako ni nga issue @Verseler

**Comment by Amawers** [comment]
ayaw kalimot pull origin both front ug backend
