### ISSUE TITLE
Same issue sa gahapon sa pag create og schedule list

### ISSUE THREAD

**Issue by Verseler** [Amawers/attendifyyy#29]
mana kog git pull sa backend og front end

![image](https://github.com/Amawers/attendifyyy/assets/121875436/8440bc8e-9b98-4f6a-9fa4-89c6c01660dd)
mao ning error
@Amawers

**Comment by Amawers** [comment]
nana kai class_schedules na table? @Verseler

**Comment by Verseler** [comment]
unsa na table pasabot nimo?

**Comment by Verseler** [comment]
ay oh sa mysql

**Comment by Amawers** [comment]
CREATE TABLE class_schedules (
    schedule_id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_id INT NOT NULL,
    subject_id INT NOT NULL,
    section_id INT NOT NULL,
    start_time TIME,
    end_time TIME,
    day_of_week TEXT,
    CONSTRAINT class_schedules_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects (subject_id),
    CONSTRAINT class_schedules_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES teachers (teacher_id),
    CONSTRAINT class_schedules_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections (section_id)
);

**Comment by Verseler** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/121875436/2077e591-c472-4c88-b45a-65b14b0a1396)
naa bagon error

**Comment by Amawers** [comment]
sakto api_connection na ip ge gamit?

**Comment by Verseler** [comment]
localhost

**Comment by Amawers** [comment]
sa subject list ra ga error?

**Comment by Verseler** [comment]
wait sorry boss
   balik lng ko unya ghe sugo pako

**Comment by Verseler** [comment]
oo boss, mo gawas na pag mag create kog class list

**Comment by Amawers** [comment]
done issue

resolve: need to specify subject name

**Comment by Amawers** [comment]
done issue

resolve: need to specify subject name
