### ISSUE TITLE
GENERAL INSTRUCTIONS BEFORE CODING

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#34]
- I'll create an issue nga kamo ra makakita, check lang gyud everytime.
- Always command "git pull origin main" in order to update your branch ( both frontend(attendify) & backend(attendify_backend) ).
- Always create pull request right after pushing.
- When encountering an error in the app nga dili inyohang part, create an issue and add relevant label (ex. bug, duplicate) to determine if need to fix asap or later pa.
- All your concerns about your part if naay error e comment lang sa katong assigned issue ninyo, ayaw pag message sa GC kai matabonan.
- Practice comment sa code ninyo para dili ko mabuang when it comes integration sa frontend ug backend
- DILI MAGPATAKAG MERGE.
- Basaha ni utro, sabta, dili mag dinumbel.

**Comment by Amawers** [comment]
Comment "goods" if nabasahan ug sabtan ayo.
@Verseler @shadowww2802 @Lindychu1 @jakkusu1 @JianSanchez

**Comment by Lindychu1** [comment]
Goods booss

**Comment by shadowww2802** [comment]
goods 🤸🏿‍♂️

**Comment by Amawers** [comment]
Figma link for design reference:

https://www.figma.com/file/ytOQeyPE76vem2DPhE04N5/Attendance-Scanner?type=design&node-id=0%3A1&mode=design&t=sfpg1GHHCr9J99gf-1

**Comment by JianSanchez** [comment]
goods na

**Comment by Verseler** [comment]
goods

**Comment by jakkusu1** [comment]
**goods**

**Comment by Amawers** [comment]
Assigned task done: @Lindychu1, proceed to review your code for preparation Q&A during presentation.
