### ISSUE TITLE
Subjects List Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#35]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/2f271830-d426-4e0e-9bad-33e01bac512b)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by Amawers** [comment]
update ani para maka integrate nako

**Comment by shadowww2802** [comment]
> update ani para maka integrate nako

di ko maka add subject sakoa gapilit sya boss

**Comment by Amawers** [comment]
nag git pull origin main naka dira?

**Comment by shadowww2802** [comment]
> nag git pull origin main naka dira?

oooh

**Comment by Amawers** [comment]
sa backend?

**Comment by shadowww2802** [comment]
> sa backend?

both mana

**Comment by Amawers** [comment]
ang e implement man nimo ani nga screen akang 3 dots bitaw sa inig taas sa kada card. Naay ing ana gyapon sa part ni verseler, tan awa gali iya code

**Comment by Amawers** [comment]
na implement na niya, igo ra nimo copy paste

**Comment by shadowww2802** [comment]
> na implement na niya, igo ra nimo copy paste

lagiii pero di nako na sya ma view basta wakoy subject list nakabutang man...

**Comment by shadowww2802** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/124649665/58df0136-f6c4-4ce4-bf79-1cccb2a2e7b6)

**Comment by Amawers** [comment]
unsay error if mag create naka?

**Comment by Amawers** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/4a6e4c3d-3b5b-47db-9ad8-f1d0d6a7e917)

sa chrome raka ga run diba? basin mali nga domain name imong gamit. Adto sa connection.dart tas e comment out tong 192.124... then e uncomment tong localhost

**Comment by shadowww2802** [comment]
> unsay error if mag create naka?

wa syay error nakabutang sa terminal... gaka call stack rasya

**Comment by shadowww2802** [comment]
> ![image](https://private-user-images.githubusercontent.com/101647124/298317631-4a6e4c3d-3b5b-47db-9ad8-f1d0d6a7e917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDQwODksIm5iZiI6MTcwNTgwMzc4OSwicGF0aCI6Ii8xMDE2NDcxMjQvMjk4MzE3NjMxLTRhNmU0YzNkLTNiNWItNDdkYi05YWQ4LWYxZDBkNmE3ZTkxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwMjIzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzY5MTM3ZDFlMDNiYTY3YTFhNWM5ZTUwZTRlZWI0ZDhjMjVmNmQxNDgyZjljMDkyYjJhYzY2OTMwMGJhN2JkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tRZeJHTahOCCDgThOlAai1JUXra2q7lk9E09TgA1ijA)
> 
> sa chrome raka ga run diba? basin mali nga domain name imong gamit. Adto sa connection.dart tas e comment out tong 192.124... then e uncomment tong localhost

goods nana sya nga part... kay maka run man kos uban screen...
![image](https://github.com/Amawers/attendifyyy/assets/124649665/aacc86a9-1d56-4a30-80f6-5cf0bff73b45)

**Comment by Amawers** [comment]
e mano2x nalang as of now didto sa database ahh, adto sa myphp admin tas manual pag butang sa subject ug subject_teachers na tables. fix rako na

**Comment by shadowww2802** [comment]
> e mano2x nalang as of now didto sa database ahh, adto sa myphp admin tas manual pag butang sa subject ug subject_teachers na tables. fix rako na

okaaay copy...

**Comment by Amawers** [comment]
paghimo issue bi para dili nako malimtan

**Comment by Amawers** [comment]
detailed description sa error/bug ahh

**Comment by shadowww2802** [comment]
asa tong table sa php? nakalimot kos unsa toy attributes HAHAHAHAHAH

**Comment by Amawers** [comment]
ISSUE RESOLVED.
