### ISSUE TITLE
Class Schedule Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#38]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/c52b7d2d-14aa-4eec-880d-86242d7335f4)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by Verseler** [comment]
Done boss

**Comment by Amawers** [comment]
Sige, pero ayaw katingala dili sa nako e merge sa main kai e try sa nako na'g integrate sa backend kung dali raba aya nako e merge @Verseler

**Comment by Verseler** [comment]
gege

**Comment by Amawers** [comment]
![417979698_888659449406075_3837036267660526379_n](https://github.com/Amawers/attendifyyy/assets/101647124/3d8510ea-d1ea-4a87-afcd-016082b74c8c)


Problem with text overflow, kulangi pa gamay ang font or logic nga mo gamay if mag overflow, tas kanang shadows ba e highlight pa siya gamay kanang maklaro gyud siya @Verseler

**Comment by Amawers** [comment]
![417677770_392553309835608_4304458380218880839_n](https://github.com/Amawers/attendifyyy/assets/101647124/22495185-4357-4c91-aa49-5b89a114ca06)

As per design sa figma, dapat dropdown ang subject name tas ang section. Put placeholder lang sa subject name ug section kai mag integrate pako ana. Ang days in a week sayop, dapat ipakita sa dropdown mga weekdays (ex. Monday, Tuesday, Wednesdays)

**Comment by Amawers** [comment]
Dropdown for days in a week done, ako na ge fix.

**Comment by Amawers** [comment]
UPDATE ISSUE TO RESOLVE:
- Overflow subject name
- Subject name and Section to be a dropdown

WHAT I FIX:
- Time picking bug, I resolve using backend
- Days in a week (Monday, Tuesday)

FEATURE/INTEGRATION I MADE:
- Add functionality for deleting a schedule, but it's not instantly refresh. Need to click the subject list button again from dashboard to refresh schedule list.

**Comment by Verseler** [comment]
- Ay ok ga overflow sya pag dako ra ang text. E try nalang nakog hide ang overloflow sa ellipsis. Kung dili makaya ako nlang pa gamayon ang font.
- ay putik ang pag sabot nako sa days of week kay kapila sa isa ka week ang klase sa subject. My bad haha 


-cge ako ng ayohon

**Comment by Amawers** [comment]
Kanang days of week implemented nana. ANd katong dropdown lang gyud sa subject ug section tas tong overflow

**Comment by Amawers** [comment]
pag git pull origin main gali

**Comment by Verseler** [comment]
Done

**Comment by Amawers** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/6c763f4f-4654-424a-a59b-bb0c1f73afe2)

Made rivision for dropdown to all in one, subject + section.

**Comment by Amawers** [comment]
ISSUE RESOLVED.

**Comment by Amawers** [comment]
KULANG PA DIAY NI, NANAY BACKEND IMONG DELETE PERO WALA PAKAY EDIT NGA UI BAI
@Verseler

**Comment by Verseler** [comment]
done

**Comment by Amawers** [comment]
ISSUE RESOLVED.
