### ISSUE TITLE
Attendance Report Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#39]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/9391355e-0c87-4a69-9a40-8fc0584e22e0)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by Verseler** [comment]
done

**Comment by Amawers** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/54300439-94d3-4484-b67c-10c04ee8e47c)


UI overflowing @Verseler

**Comment by Verseler** [comment]
done

**Comment by Amawers** [comment]
ISSUE RESOLVED.
