### ISSUE TITLE
Before Selecting Subject Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#40]
![image](https://github.com/Amawers/attendifyyy/assets/101647124/ca0d9f0e-cc2d-4d3b-af27-3cefe22b5504)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by jakkusu1** [comment]
Pop-up dialog ra ning "Select chuchu" ba?

**Comment by Amawers** [comment]
drop-down or pop-up, basta ang importante maka select ug specific subject @jakkusu1

**Comment by jakkusu1** [comment]
oke oke copy

**Comment by Amawers** [comment]
ISSUE RESOLVED.
