### ISSUE TITLE
Privacy Policy Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#43]
USE THIS REFERENCE
![image](https://github.com/Amawers/attendifyyy/assets/101647124/42f30439-64ae-4ba8-b5e3-683e2a3c5277)

TO FIX THIS!
![417750925_201385522996669_1065955788477231559_n](https://github.com/Amawers/attendifyyy/assets/101647124/e0c56e72-c290-4761-927e-827a7552d077)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by JianSanchez** [comment]
copyyy

**Comment by Amawers** [comment]
ISSUE RESOLVED.
