### ISSUE TITLE
Contact Support Screen

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#44]
USE THIS REFERENCE
![image](https://github.com/Amawers/attendifyyy/assets/101647124/91b346c9-8bc6-4aa1-a4d0-b4bed817742f)

TO FIX THIS!
![418304566_3050947308376116_5378785954515293976_n](https://github.com/Amawers/attendifyyy/assets/101647124/96252e6f-b041-4d35-a0a6-e3de6eae8a1b)

Detailed instruction in figma, follow.
Kanang sa appbar lahi magimplement ana, focus sa body.

**Comment by JianSanchez** [comment]
copyyyy

**Comment by Amawers** [comment]
ISSUE RESOLVED.
