### ISSUE TITLE
All Screen Implementation

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#46]
Implement this in screens accoding to the figma design:
![image](https://github.com/Amawers/attendifyyy/assets/101647124/717f175a-390d-490b-a101-e5a5d4c0af96)

![image](https://github.com/Amawers/attendifyyy/assets/101647124/409feb92-d68a-4fd0-9101-bea80b0e6cf2)

The first image with logo is already created, kindly refer to "about app" screen in order to copy paste nalang ang code.

**Comment by Lindychu1** [comment]
geggegeges

**Comment by Lindychu1** [comment]
![image](https://github.com/Amawers/attendifyyy/assets/124657181/e8c793ab-2be0-48b4-a232-f00d44a6c848)

**Comment by Lindychu1** [comment]
Done implementing Title Appbar adn Logo:
Manage Account
![image](https://github.com/Amawers/attendifyyy/assets/124657181/2deeaee3-44b9-491f-bb8c-eb4de91c9e66)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/5452166b-4e23-4f11-8293-749abd623959)
Settings

![image](https://github.com/Amawers/attendifyyy/assets/124657181/32f87c79-2220-4b52-9853-2d23425dbdfb)
contact Support

![image](https://github.com/Amawers/attendifyyy/assets/124657181/f1ab7aa8-a57c-4e9f-8f21-b86104b9a707)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/8e02bc1b-833d-491e-b39a-65fe3fe238f6)

Done creating  about app 

![image](https://github.com/Amawers/attendifyyy/assets/124657181/f944d4c6-42f3-4c5e-b592-2ebf0a848402)

Qr Scan


![image](https://github.com/Amawers/attendifyyy/assets/124657181/10d75ebb-a782-4f37-8318-47dfed5ec92a)
Student List (already Implemented)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/081a579e-d1ec-437c-921f-34c4339ccf36)
Schedule List (already Implemented)


![image](https://github.com/Amawers/attendifyyy/assets/124657181/bc727206-84ca-466d-bc64-e1f93006f1c8)

Subject  List (already Implemented)


Still on Progress 
dashboard

**Comment by Lindychu1** [comment]
code for appbar (TexT )

![image](https://github.com/Amawers/attendifyyy/assets/124657181/f2154ac5-3d41-419a-9fe7-953fbbf106aa)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/70903b67-5560-44c9-99dc-c2b65b26980c)
Code for Appbar (Logo)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/25a6c034-bd96-4120-b604-7fa7154bbcd2)

![image](https://github.com/Amawers/attendifyyy/assets/124657181/b84e4e3a-de58-4601-aabf-bfa341a1534a)

**Comment by Amawers** [comment]
ISSUE RESOLVED.
