### ISSUE TITLE
Selected Start-End Time Not Reflecting

### ISSUE THREAD

**Issue by jakkusu1** [Amawers/attendifyyy#53]
![image](https://github.com/Amawers/attendifyyy/assets/125298815/ece96ec6-3cd0-48bb-b781-34da00910fc1)
![image](https://github.com/Amawers/attendifyyy/assets/125298815/54f2faf0-93e0-49f0-be98-abe0d94c49b1)

**Comment by jakkusu1** [comment]
Ay karon pako kabantay na somewhat na discuss na ni ninyo ni Verseler. Pero myes inana siya sa akoang end. 

Also, day of the week diay na diay? HAHAHAHAH. "1" ako nabutang kay abi nako ang pasabot ana na field kay ikapila mag repeat per week. Mas better if naka drop down jud ata na diha.

**Comment by Amawers** [comment]
Done nani nga implementation. Ge fix nako kagabie, pag git pull origin main both front & backend lang. I'll close this issue if maka reply naka nga goods na in your end.

**Comment by Amawers** [comment]
ISSUE RESOLVED.
