### ISSUE TITLE
Limpyo Code VERSELER

### ISSUE THREAD

**Issue by Amawers** [Amawers/attendifyyy#71]
- Create Schedules
- Attendance
- Core
- Scanning Qr

**Each feature/folder create a sub-folder name "widgets" to store reusable widgets**.

@Verseler

**Comment by Verseler** [comment]
boss 

![image](https://github.com/Amawers/attendifyyy/assets/121875436/9629e89f-43a7-47ea-a98e-ce19cf327a81)

**Comment by Amawers** [comment]
unsa na?

**Comment by Verseler** [comment]
sa dashboard

**Comment by Verseler** [comment]
naay gagawas na failed to fetch schedules

**Comment by Amawers** [comment]
unsa na screen imo ge click?

**Comment by Verseler** [comment]
pag login palang

pag human mo gawas ang login successfully

**Comment by Verseler** [comment]
og taga balhin nakog laing page pag balik s adashboard mo gawas dayun sya

**Comment by Amawers** [comment]
normal raman sa ako, ayaw nalang sa kaayo e mind na, ako rana e handle proper

**Comment by Verseler** [comment]
boss wala nako ghe apil ang scanning qr bay

basin naay ma daot bay
dili nako ma test kay web rako

kamo nalang sa sa scanning qr

kay ako naning e push

**Comment by Amawers** [comment]
gegeggegege

**Comment by Verseler** [comment]
Done

**Comment by Amawers** [comment]
ISSUE RESOLVED.
